version: 2.1
orbs:
    node: circleci/node@5.0.2
    aws-cli: circleci/aws-cli@2.0.0
    aws-s3: circleci/aws-s3@3.0.0
    aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
    frontend:
        working_directory: ~/app/udagram-frontend
        executor: node/default
        steps:
            - checkout:
                  path: ~/app
            - node/install-packages:
                  app-dir: ~/app/udagram-frontend
            - run:
                  name: Building Frontend
                  command: npm run build
            - aws-cli/install
            - aws-s3/copy:
                  from: ./www
                  to: $S3_BUCKET_FRONTEND
                  arguments: --recursive --acl public-read
    server:
        working_directory: ~/app/udagram-api
        executor: node/default
        steps:
            - checkout:
                  path: ~/app
            - node/install-packages:
                  app-dir: ~/app/udagram-api
            - run:
                  name: Building and Archiving Server
                  command: |-
                      npm run build
                      printenv > www/.env
                      npm run create_archive
            - aws-cli/install
            - aws-s3/copy:
                  from: ./www/Project.zip
                  to: $S3_BUCKET_SERVER
            - run:
                  name: Deploy Server (EB)
                  command: |-
                      aws elasticbeanstalk create-application-version --application-name $EB_APP --version-label <<pipeline.git.revision>> --source-bundle S3Bucket=$EB_BUCKET,S3Key="Project.zip"
                      aws elasticbeanstalk update-environment --application-name $EB_APP --environment-name $EB_ENV --version-label <<pipeline.git.revision>>
workflows:
    build_and_deploy:
        jobs:
            - frontend
            - server
